version: '3'

services:
  financeetl:
    image: financeetl:latest
    
    volumes:
      - ./airflow:/opt/airflow

    ports:
      - "8080:8080"
    
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db

    command: airflow standalone